# Site settings
theme: jekyll-theme-merlot

title: Westminster Math Tutor

description: > # this means to ignore newlines until "baseurl:"
  Renee Swindle - (303)469-9537 - reneeswindle@yahoo.com
baseurl: '' # the subpath of your site, e.g. /blog
# Bad things happen if that is set to '/'

url: "http://the-whiteboard.github.io" # the base hostname & protocol for your site

github:
  repo: 'https://github.com/WestminsterMathTutor'
  user: 'WestminsterMathTutor'

# Build settings
markdown: kramdown
